.Dt NATPMPD 8
.Os
.Sh NAME
.Nm natpmpd
.Nd NAT-PMP daemon
.Sh SYNOPSIS
.Nm natpmpd
.Op Fl dv
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm
is a daemon which implements the NAT-PMP protocol.
.Sh FILES
.Bl -tag -compact
.It Pa /etc/natpmpd.conf
default
.Nm
configuration file
.El
.Sh SEE ALSO
.Xr natpmpd.conf 5
.Sh AUTHORS
The
.Nm
program was written by
.An Matt Dainty Aq matt@bodgit-n-scarper.com .
