.Dt NATPMPD.CONF 5
.Os
.Sh NAME
.Nm natpmpd.conf
.Nd NAT-PMP daemon configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for the
.Xr natpmpd 8
daemon.
.Sh SECTIONS
.Sh FILES
.Bl -tag -compact
.It Pa /etc/natpmpd.conf
Default location of the configuration file.
.El
.Sh EXAMPLES
.Sh SEE ALSO
.Xr natpmpd 8
.Sh AUTHORS
The
.Xr natpmpd 8
program was written by
.An Matt Dainty Aq matt@bodgit-n-scarper.com .
