.\" $Id$
.\"
.\" Copyright (c) 2010 Matt Dainty <matt@bodgit-n-scarper.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt NATPMPD 8
.Os
.Sh NAME
.Nm natpmpd
.Nd NAT-PMP daemon
.Sh SYNOPSIS
.Nm natpmpd
.Op Fl dnv
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm
is a daemon which implements the NAT-PMP protocol.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Do not daemonize and log to
.Em stderr .
.It Fl f Ar file
Use
.Ar file
as the configuration file, instead of the default
.Pa /etc/natpmpd.conf .
.It Fl n
Configtest mode.
Only check the configuration file for validity.
.It Fl v
Produce more verbose output.
.El
.Sh CONFIGURATION
To allow
.Nm
to create mappings,
.Xr pf.conf 5
needs the following rule.
.Bd -literal -offset 2n
anchor "natpmpd"
.Ed
.Sh FILES
.Bl -tag -compact
.It Pa /etc/natpmpd.conf
default
.Nm
configuration file
.El
.Sh SEE ALSO
.Xr natpmpd.conf 5 ,
.Xr pf 4 ,
.Xr pf.conf 5
.Rs
.%R RFC 6886
.%T "NAT Port Mapping Protocol (NAT-PMP)"
.%D April 2013
.Re
.Sh CAVEATS
.Xr pf 4
does not allow the ruleset to be modified if the system is running at a
.Xr securelevel 7
higher than 1.
At that level
.Nm
cannot add rules to the anchors and NAT-PMP requests will not work.
.Sh AUTHORS
The
.Nm
program was written by
.An Matt Dainty Aq matt@bodgit-n-scarper.com .
